-- Mensagens diárias cristocêntricas (protestantes / reformadas / evangélicas)
CREATE TABLE IF NOT EXISTS mensagem_diaria (
  id BIGSERIAL PRIMARY KEY,
  dia_ano SMALLINT NOT NULL,
  texto TEXT NOT NULL,
  referencia VARCHAR(160),
  tipo VARCHAR(30) NOT NULL DEFAULT 'versiculo',
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uk_mensagem_diaria_dia UNIQUE (dia_ano),
  CONSTRAINT ck_mensagem_diaria_dia CHECK (dia_ano BETWEEN 1 AND 366),
  CONSTRAINT ck_mensagem_diaria_tipo CHECK (tipo IN ('versiculo', 'citacao', 'animo'))
);

CREATE INDEX IF NOT EXISTS idx_mensagem_diaria_ativo ON mensagem_diaria (ativo);

COMMENT ON TABLE mensagem_diaria IS 'Uma mensagem cristocêntrica por dia do ano (1-366).';

INSERT INTO mensagem_diaria (dia_ano, texto, referencia, tipo, ativo) VALUES
(1, 'Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna.', 'João 3:16', 'versiculo', TRUE),
(2, 'Tudo posso naquele que me fortalece.', 'Filipenses 4:13', 'versiculo', TRUE),
(3, 'O Senhor é o meu pastor; nada me faltará.', 'Salmos 23:1', 'versiculo', TRUE),
(4, 'Entrega o teu caminho ao Senhor; confia nele, e ele tudo fará.', 'Salmos 37:5', 'versiculo', TRUE),
(5, 'Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus.', 'Isaías 41:10', 'versiculo', TRUE),
(6, 'Buscai primeiro o Reino de Deus, e a sua justiça, e todas estas coisas vos serão acrescentadas.', 'Mateus 6:33', 'versiculo', TRUE),
(7, 'Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei.', 'Mateus 11:28', 'versiculo', TRUE),
(8, 'Eu sou o caminho, e a verdade, e a vida; ninguém vem ao Pai senão por mim.', 'João 14:6', 'versiculo', TRUE),
(9, 'Se Deus é por nós, quem será contra nós?', 'Romanos 8:31', 'versiculo', TRUE),
(10, 'Todas as coisas cooperam para o bem daqueles que amam a Deus.', 'Romanos 8:28', 'versiculo', TRUE),
(11, 'O amor é paciente, o amor é bondoso. Não inveja, não se vangloria, não se orgulha.', '1 Coríntios 13:4', 'versiculo', TRUE),
(12, 'Sejam fortes e corajosos. Não tenham medo nem fiquem apavorados, pois o Senhor, o seu Deus, vai com vocês.', 'Deuteronômio 31:6', 'versiculo', TRUE),
(13, 'Lança o teu cuidado sobre o Senhor, e ele te susterá.', 'Salmos 55:22', 'versiculo', TRUE),
(14, 'A alegria do Senhor é a nossa força.', 'Neemias 8:10', 'versiculo', TRUE),
(15, 'Confia no Senhor de todo o teu coração e não te estribes no teu próprio entendimento.', 'Provérbios 3:5', 'versiculo', TRUE),
(16, 'Em todas as tuas vias reconhece-o, e ele endireitará as tuas veredas.', 'Provérbios 3:6', 'versiculo', TRUE),
(17, 'Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará.', 'Salmos 91:1', 'versiculo', TRUE),
(18, 'O Senhor é a minha luz e a minha salvação; a quem temerei?', 'Salmos 27:1', 'versiculo', TRUE),
(19, 'Cria em mim, ó Deus, um coração puro e renova em mim um espírito reto.', 'Salmos 51:10', 'versiculo', TRUE),
(20, 'Bem-aventurados os que têm fome e sede de justiça, porque eles serão fartos.', 'Mateus 5:6', 'versiculo', TRUE),
(21, 'Vós sois a luz do mundo; não se pode esconder uma cidade edificada sobre um monte.', 'Mateus 5:14', 'versiculo', TRUE),
(22, 'Assim brilhe a vossa luz diante dos homens, para que vejam as vossas boas obras e glorifiquem a vosso Pai.', 'Mateus 5:16', 'versiculo', TRUE),
(23, 'Não andeis ansiosos de coisa alguma; antes, em tudo, sejam os vossos pedidos conhecidos diante de Deus.', 'Filipenses 4:6', 'versiculo', TRUE),
(24, 'E a paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos sentimentos em Cristo Jesus.', 'Filipenses 4:7', 'versiculo', TRUE),
(25, 'Porque pela graça sois salvos, por meio da fé; e isto não vem de vós; é dom de Deus.', 'Efésios 2:8', 'versiculo', TRUE),
(26, 'Revesti-vos de toda a armadura de Deus, para que possais estar firmes contra as ciladas do diabo.', 'Efésios 6:11', 'versiculo', TRUE),
(27, 'Sede, pois, imitadores de Deus, como filhos amados.', 'Efésios 5:1', 'versiculo', TRUE),
(28, 'Andai em amor, como também Cristo vos amou.', 'Efésios 5:2', 'versiculo', TRUE),
(29, 'O fruto do Espírito é: amor, alegria, paz, longanimidade, benignidade, bondade, fidelidade.', 'Gálatas 5:22', 'versiculo', TRUE),
(30, 'Já não sou eu quem vive, mas Cristo vive em mim.', 'Gálatas 2:20', 'versiculo', TRUE),
(31, 'Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna em Cristo Jesus.', 'Romanos 6:23', 'versiculo', TRUE),
(32, 'Não vos conformeis com este século, mas transformai-vos pela renovação da vossa mente.', 'Romanos 12:2', 'versiculo', TRUE),
(33, 'Amai-vos cordialmente uns aos outros com amor fraternal.', 'Romanos 12:10', 'versiculo', TRUE),
(34, 'Eis que estou à porta e bato; se alguém ouvir a minha voz e abrir a porta, entrarei.', 'Apocalipse 3:20', 'versiculo', TRUE),
(35, 'Eu sou o Alfa e o Ômega, o princípio e o fim, diz o Senhor.', 'Apocalipse 1:8', 'versiculo', TRUE),
(36, 'Sede santos, porque eu sou santo.', '1 Pedro 1:16', 'versiculo', TRUE),
(37, 'Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.', '1 Pedro 5:7', 'versiculo', TRUE),
(38, 'Mas o Deus de toda a graça… vos aperfeiçoará, confirmará, fortificará e estabelecerá.', '1 Pedro 5:10', 'versiculo', TRUE),
(39, 'Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar e nos purificar.', '1 João 1:9', 'versiculo', TRUE),
(40, 'Nós amamos porque ele nos amou primeiro.', '1 João 4:19', 'versiculo', TRUE),
(41, 'Deus é amor; e quem permanece em amor permanece em Deus, e Deus nele.', '1 João 4:16', 'versiculo', TRUE),
(42, 'A fé é o firme fundamento das coisas que se esperam e a prova das coisas que se não veem.', 'Hebreus 11:1', 'versiculo', TRUE),
(43, 'Olhando firmemente para o Autor e Consumador da fé, Jesus.', 'Hebreus 12:2', 'versiculo', TRUE),
(44, 'Acheguemo-nos, pois, com confiança ao trono da graça, para que alcancemos misericórdia.', 'Hebreus 4:16', 'versiculo', TRUE),
(45, 'Jesus Cristo é o mesmo ontem, e hoje, e eternamente.', 'Hebreus 13:8', 'versiculo', TRUE),
(46, 'Sede dores da palavra, e não somente ouvintes.', 'Tiago 1:22', 'versiculo', TRUE),
(47, 'A oração feita por um justo pode muito em seus efeitos.', 'Tiago 5:16', 'versiculo', TRUE),
(48, 'O Senhor é bom, um refúgio em tempos de angústia; conhece os que nele confiam.', 'Naum 1:7', 'versiculo', TRUE),
(49, 'Ainda que a figueira não floresça… eu me alegrarei no Senhor.', 'Habacuque 3:17-18', 'versiculo', TRUE),
(50, 'Porque eu bem sei os planos que tenho a vosso respeito, diz o Senhor; planos de paz e não de mal.', 'Jeremias 29:11', 'versiculo', TRUE),
(51, 'Clama a mim, e responder-te-ei e anunciar-te-ei coisas grandes e firmes.', 'Jeremias 33:3', 'versiculo', TRUE),
(52, 'As misericórdias do Senhor são a causa de não sermos consumidos; renovam-se a cada manhã.', 'Lamentações 3:22-23', 'versiculo', TRUE),
(53, 'Eis que faço uma coisa nova; agora sairá à luz; porventura não a percebeis?', 'Isaías 43:19', 'versiculo', TRUE),
(54, 'Mas os que esperam no Senhor renovarão as suas forças; subirão com asas como águias.', 'Isaías 40:31', 'versiculo', TRUE),
(55, 'O Senhor pelejará por vós, e vós vos calareis.', 'Êxodo 14:14', 'versiculo', TRUE),
(56, 'Sede fortes e corajosos; não temais, porque o Senhor vosso Deus é o que vai convosco.', 'Deuteronômio 31:6', 'versiculo', TRUE),
(57, 'Escolhei hoje a quem sirvais… eu e a minha casa serviremos ao Senhor.', 'Josué 24:15', 'versiculo', TRUE),
(58, 'Não por força nem por poder, mas pelo meu Espírito, diz o Senhor dos Exércitos.', 'Zacarias 4:6', 'versiculo', TRUE),
(59, 'Amarás o Senhor teu Deus de todo o teu coração… e ao teu próximo como a ti mesmo.', 'Mateus 22:37-39', 'versiculo', TRUE),
(60, 'Ide, portanto, fazei discípulos de todas as nações.', 'Mateus 28:19', 'versiculo', TRUE),
(61, 'Eis que eu estou convosco todos os dias, até a consumação dos séculos.', 'Mateus 28:20', 'versiculo', TRUE),
(62, 'O Filho do Homem veio buscar e salvar o que se havia perdido.', 'Lucas 19:10', 'versiculo', TRUE),
(63, 'Porque o Filho do Homem não veio para ser servido, mas para servir e dar a sua vida.', 'Marcos 10:45', 'versiculo', TRUE),
(64, 'Arrependei-vos, porque é chegado o Reino dos céus.', 'Mateus 4:17', 'versiculo', TRUE),
(65, 'Bem-aventurados os pacificadores, porque eles serão chamados filhos de Deus.', 'Mateus 5:9', 'versiculo', TRUE),
(66, 'Não julgueis, para que não sejais julgados.', 'Mateus 7:1', 'versiculo', TRUE),
(67, 'Pedi, e dar-se-vos-á; buscai, e encontrareis; batei, e abrir-se-vos-á.', 'Mateus 7:7', 'versiculo', TRUE),
(68, 'Entrai pela porta estreita… estreito é o caminho que conduz à vida.', 'Mateus 7:13-14', 'versiculo', TRUE),
(69, 'Nem só de pão viverá o homem, mas de toda palavra que sai da boca de Deus.', 'Mateus 4:4', 'versiculo', TRUE),
(70, 'Onde estiver o vosso tesouro, aí estará também o vosso coração.', 'Mateus 6:21', 'versiculo', TRUE),
(71, 'Não podeis servir a Deus e às riquezas.', 'Mateus 6:24', 'versiculo', TRUE),
(72, 'Basta a cada dia o seu mal.', 'Mateus 6:34', 'versiculo', TRUE),
(73, 'Aquele que crê em mim, como diz a Escritura, rios de água viva correrão do seu interior.', 'João 7:38', 'versiculo', TRUE),
(74, 'Conhecereis a verdade, e a verdade vos libertará.', 'João 8:32', 'versiculo', TRUE),
(75, 'Eu sou a porta; se alguém entrar por mim, salvar-se-á.', 'João 10:9', 'versiculo', TRUE),
(76, 'Eu sou o bom Pastor; o bom Pastor dá a sua vida pelas ovelhas.', 'João 10:11', 'versiculo', TRUE),
(77, 'Eu sou a ressurreição e a vida; quem crê em mim, ainda que esteja morto, viverá.', 'João 11:25', 'versiculo', TRUE),
(78, 'Um novo mandamento vos dou: que vos ameis uns aos outros como eu vos amei.', 'João 13:34', 'versiculo', TRUE),
(79, 'Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá.', 'João 14:27', 'versiculo', TRUE),
(80, 'Eu sou a videira verdadeira, e meu Pai é o lavrador.', 'João 15:1', 'versiculo', TRUE),
(81, 'Sem mim nada podeis fazer.', 'João 15:5', 'versiculo', TRUE),
(82, 'Ninguém tem maior amor do que este: de dar alguém a sua vida pelos seus amigos.', 'João 15:13', 'versiculo', TRUE),
(83, 'Santifica-os na verdade; a tua palavra é a verdade.', 'João 17:17', 'versiculo', TRUE),
(84, 'Está consumado!', 'João 19:30', 'versiculo', TRUE),
(85, 'Recebei o Espírito Santo.', 'João 20:22', 'versiculo', TRUE),
(86, 'Mas recebereis poder, ao descer sobre vós o Espírito Santo, e ser-me-eis testemunhas.', 'Atos 1:8', 'versiculo', TRUE),
(87, 'Não há salvação em nenhum outro; porque debaixo do céu nenhum outro nome há… pelo qual haja de ser salvo.', 'Atos 4:12', 'versiculo', TRUE),
(88, 'Crê no Senhor Jesus Cristo e serás salvo, tu e a tua casa.', 'Atos 16:31', 'versiculo', TRUE),
(89, 'Porque nele vivemos, e nos movemos, e existimos.', 'Atos 17:28', 'versiculo', TRUE),
(90, 'Arrependei-vos, pois, e convertei-vos, para que sejam apagados os vossos pecados.', 'Atos 3:19', 'versiculo', TRUE),
(91, 'Justificados, pois, pela fé, temos paz com Deus por nosso Senhor Jesus Cristo.', 'Romanos 5:1', 'versiculo', TRUE),
(92, 'Mas Deus prova o seu amor para conosco em que Cristo morreu por nós, sendo nós ainda pecadores.', 'Romanos 5:8', 'versiculo', TRUE),
(93, 'Porque o que a lei não podia fazer… Deus, enviando o seu Filho… condenou o pecado na carne.', 'Romanos 8:3', 'versiculo', TRUE),
(94, 'O Espírito mesmo testifica com o nosso espírito que somos filhos de Deus.', 'Romanos 8:16', 'versiculo', TRUE),
(95, 'Quem nos separará do amor de Cristo?', 'Romanos 8:35', 'versiculo', TRUE),
(96, 'Em todas estas coisas somos mais que vencedores, por aquele que nos amou.', 'Romanos 8:37', 'versiculo', TRUE),
(97, 'Porque dele, e por ele, e para ele são todas as coisas; glória, pois, a ele eternamente. Amém.', 'Romanos 11:36', 'versiculo', TRUE),
(98, 'Apresentai os vossos corpos em sacrifício vivo, santo e agradável a Deus.', 'Romanos 12:1', 'versiculo', TRUE),
(99, 'Não vos vingueis a vós mesmos… Dai lugar à ira de Deus.', 'Romanos 12:19', 'versiculo', TRUE),
(100, 'Não sejais vencidos do mal, mas vencei o mal com o bem.', 'Romanos 12:21', 'versiculo', TRUE),
(101, 'A ninguém deveis coisa alguma, a não ser o amor com que vos ameis uns aos outros.', 'Romanos 13:8', 'versiculo', TRUE),
(102, 'Porque o reino de Deus não é comida nem bebida, mas justiça, e paz, e alegria no Espírito Santo.', 'Romanos 14:17', 'versiculo', TRUE),
(103, 'Ora, o Deus de esperança vos encha de todo o gozo e paz no vosso crer.', 'Romanos 15:13', 'versiculo', TRUE),
(104, 'Porque a palavra da cruz… para nós, que somos salvos, é o poder de Deus.', '1 Coríntios 1:18', 'versiculo', TRUE),
(105, 'Mas, como está escrito: As coisas que o olho não viu… são as que Deus preparou para os que o amam.', '1 Coríntios 2:9', 'versiculo', TRUE),
(106, 'Não sabeis que sois o templo de Deus e que o Espírito de Deus habita em vós?', '1 Coríntios 3:16', 'versiculo', TRUE),
(107, 'Portanto, quer comais, quer bebais ou façais outra qualquer coisa, fazei tudo para a glória de Deus.', '1 Coríntios 10:31', 'versiculo', TRUE),
(108, 'O amor nunca falha.', '1 Coríntios 13:8', 'versiculo', TRUE),
(109, 'Agora, pois, permanecem a fé, a esperança e o amor, estes três; porém o maior destes é o amor.', '1 Coríntios 13:13', 'versiculo', TRUE),
(110, 'Mas graças a Deus, que nos dá a vitória por nosso Senhor Jesus Cristo.', '1 Coríntios 15:57', 'versiculo', TRUE),
(111, 'Portanto, meus amados irmãos, sede firmes… sabendo que o vosso trabalho não é vão no Senhor.', '1 Coríntios 15:58', 'versiculo', TRUE),
(112, 'Porque o amor de Cristo nos constrange.', '2 Coríntios 5:14', 'versiculo', TRUE),
(113, 'Se alguém está em Cristo, nova criatura é; as coisas antigas já passaram; eis que tudo se fez novo.', '2 Coríntios 5:17', 'versiculo', TRUE),
(114, 'Aquele que não conheceu pecado, o fez pecado por nós, para que nele fôssemos feitos justiça de Deus.', '2 Coríntios 5:21', 'versiculo', TRUE),
(115, 'A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza.', '2 Coríntios 12:9', 'versiculo', TRUE),
(116, 'Quando estou fraco, então sou forte.', '2 Coríntios 12:10', 'versiculo', TRUE),
(117, 'Olhai por vós mesmos, que não percais o que temos ganho.', '2 João 1:8', 'versiculo', TRUE),
(118, 'Andai como convém aos chamados… com toda a humildade e mansidão.', 'Efésios 4:1-2', 'versiculo', TRUE),
(119, 'Antes sede uns para com os outros benignos, misericordiosos, perdoando-vos.', 'Efésios 4:32', 'versiculo', TRUE),
(120, 'Falai a verdade cada um com o seu próximo.', 'Efésios 4:25', 'versiculo', TRUE),
(121, 'Não entristeçais o Espírito Santo de Deus.', 'Efésios 4:30', 'versiculo', TRUE),
(122, 'Tende cuidado… de como andais; não como néscios, mas como sábios.', 'Efésios 5:15', 'versiculo', TRUE),
(123, 'Remindo o tempo, porquanto os dias são maus.', 'Efésios 5:16', 'versiculo', TRUE),
(124, 'Porque não temos que lutar contra a carne e o sangue… mas contra as potestades.', 'Efésios 6:12', 'versiculo', TRUE),
(125, 'Tomai também o capacete da salvação e a espada do Espírito, que é a palavra de Deus.', 'Efésios 6:17', 'versiculo', TRUE),
(126, 'Orando em todo tempo com toda a oração e súplica no Espírito.', 'Efésios 6:18', 'versiculo', TRUE),
(127, 'Para mim o viver é Cristo, e o morrer é ganho.', 'Filipenses 1:21', 'versiculo', TRUE),
(128, 'Nada façais por contenda ou por vanglória, mas por humildade.', 'Filipenses 2:3', 'versiculo', TRUE),
(129, 'Haja em vós o mesmo sentimento que houve também em Cristo Jesus.', 'Filipenses 2:5', 'versiculo', TRUE),
(130, 'E, achado como homem, humilhou-se a si mesmo, sendo obediente até à morte, e morte de cruz.', 'Filipenses 2:8', 'versiculo', TRUE),
(131, 'Para que ao nome de Jesus se dobre todo joelho.', 'Filipenses 2:10', 'versiculo', TRUE),
(132, 'Regozijai-vos sempre no Senhor; outra vez digo: regozijai-vos.', 'Filipenses 4:4', 'versiculo', TRUE),
(133, 'A vossa moderação seja conhecida de todos os homens. Perto está o Senhor.', 'Filipenses 4:5', 'versiculo', TRUE),
(134, 'Finalmente, irmãos, tudo o que é verdadeiro… pensai nestas coisas.', 'Filipenses 4:8', 'versiculo', TRUE),
(135, 'O meu Deus, segundo as suas riquezas, suprirá todas as vossas necessidades em glória, por Cristo Jesus.', 'Filipenses 4:19', 'versiculo', TRUE),
(136, 'Nele estão escondidos todos os tesouros da sabedoria e da ciência.', 'Colossenses 2:3', 'versiculo', TRUE),
(137, 'Assim como recebestes o Senhor Jesus Cristo, assim também andai nele.', 'Colossenses 2:6', 'versiculo', TRUE),
(138, 'Se já ressuscitastes com Cristo, buscai as coisas que são de cima.', 'Colossenses 3:1', 'versiculo', TRUE),
(139, 'Pensai nas coisas que são de cima, e não nas que são da terra.', 'Colossenses 3:2', 'versiculo', TRUE),
(140, 'E tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor.', 'Colossenses 3:23', 'versiculo', TRUE),
(141, 'A palavra de Cristo habite em vós abundantemente.', 'Colossenses 3:16', 'versiculo', TRUE),
(142, 'Sede perseverantes na oração, velando nela com ação de graças.', 'Colossenses 4:2', 'versiculo', TRUE),
(143, 'Andai com sabedoria para com os que estão de fora, remindo o tempo.', 'Colossenses 4:5', 'versiculo', TRUE),
(144, 'A nossa palavra seja sempre agradável, temperada com sal.', 'Colossenses 4:6', 'versiculo', TRUE),
(145, 'Porque o mesmo Senhor descerá do céu… e os mortos em Cristo ressuscitarão primeiro.', '1 Tessalonicenses 4:16', 'versiculo', TRUE),
(146, 'Regozijai-vos sempre. Orai sem cessar. Em tudo dai graças.', '1 Tessalonicenses 5:16-18', 'versiculo', TRUE),
(147, 'Provai tudo. Retende o bem.', '1 Tessalonicenses 5:21', 'versiculo', TRUE),
(148, 'Fiel é o que vos chama, o qual também o fará.', '1 Tessalonicenses 5:24', 'versiculo', TRUE),
(149, 'Não nos cansemos de fazer o bem, porque a seu tempo ceifaremos.', 'Gálatas 6:9', 'versiculo', TRUE),
(150, 'Levai as cargas uns dos outros e assim cumprireis a lei de Cristo.', 'Gálatas 6:2', 'versiculo', TRUE),
(151, 'Mas longe esteja de mim gloriar-me, a não ser na cruz de nosso Senhor Jesus Cristo.', 'Gálatas 6:14', 'versiculo', TRUE),
(152, 'Combati o bom combate, acabei a carreira, guardei a fé.', '2 Timóteo 4:7', 'versiculo', TRUE),
(153, 'Toda a Escritura é divinamente inspirada e proveitosa.', '2 Timóteo 3:16', 'versiculo', TRUE),
(154, 'Porque Deus não nos deu o espírito de temor, mas de fortaleza, e de amor, e de moderação.', '2 Timóteo 1:7', 'versiculo', TRUE),
(155, 'Prega a palavra, insta a tempo e fora de tempo.', '2 Timóteo 4:2', 'versiculo', TRUE),
(156, 'Fiel é esta palavra: Se com ele morrermos, também com ele viveremos.', '2 Timóteo 2:11', 'versiculo', TRUE),
(157, 'Procura apresentar-te a Deus aprovado, como obreiro que não tem de que se envergonhar.', '2 Timóteo 2:15', 'versiculo', TRUE),
(158, 'A aparência da piedade… negando a eficácia dela. Aparta-te também destes.', '2 Timóteo 3:5', 'versiculo', TRUE),
(159, 'Porque a graça de Deus se há manifestado… ensinando-nos que… vivamos no presente século sóbria, justa e piamente.', 'Tito 2:11-12', 'versiculo', TRUE),
(160, 'Não por obras de justiça que houvéssemos feito, mas segundo a sua misericórdia, nos salvou.', 'Tito 3:5', 'versiculo', TRUE),
(161, 'Porque a nossa leve e momentânea tribulação produz… eterno peso de glória.', '2 Coríntios 4:17', 'versiculo', TRUE),
(162, 'Não atentando nós nas coisas que se veem, mas nas que se não veem.', '2 Coríntios 4:18', 'versiculo', TRUE),
(163, 'Andamos por fé, e não por vista.', '2 Coríntios 5:7', 'versiculo', TRUE),
(164, 'A Bíblia é a âncora da minha alma.', 'Billy Graham', 'citacao', TRUE),
(165, 'Deus tem um plano para cada vida, e esse plano inclui a cruz e a ressurreição de Cristo.', 'Billy Graham', 'citacao', TRUE),
(166, 'Ser cristão não é apenas fazer o bem; é uma relação viva com Jesus Cristo.', 'Billy Graham', 'citacao', TRUE),
(167, 'O evangelho não é um debate; é um anúncio: Cristo morreu e ressuscitou.', 'Billy Graham', 'citacao', TRUE),
(168, 'Quando Cristo entra na vida, tudo muda — o coração, os valores e a eternidade.', 'Billy Graham', 'citacao', TRUE),
(169, 'A fé é uma resposta confiante ao Deus que fala na Escritura.', 'João Calvino', 'citacao', TRUE),
(170, 'O coração do homem é uma fábrica permanente de ídolos; só Cristo o liberta.', 'João Calvino', 'citacao', TRUE),
(171, 'Somos salvos pela graça, mediante a fé — não por mérito nosso.', 'João Calvino', 'citacao', TRUE),
(172, 'A verdadeira sabedoria consiste em conhecer a Deus e a nós mesmos em Cristo.', 'João Calvino', 'citacao', TRUE),
(173, 'A Escritura é o espelho em que contemplamos o rosto de Deus.', 'João Calvino', 'citacao', TRUE),
(174, 'A fé é uma confiança viva e ousada na graça de Deus, tão certa que arriscaria mil vezes a vida nela.', 'Martinho Lutero', 'citacao', TRUE),
(175, 'Cristo é o Senhor da Escritura; fora dele a Bíblia se torna letra morta.', 'Martinho Lutero', 'citacao', TRUE),
(176, 'O justo viverá pela fé — esta é a porta da liberdade cristã.', 'Martinho Lutero', 'citacao', TRUE),
(177, 'Ore como se tudo dependesse de Deus; trabalhe como se tudo dependesse de você.', 'Martinho Lutero', 'citacao', TRUE),
(178, 'A consciência cativa à Palavra de Deus não pode se dobrar a homens.', 'Martinho Lutero', 'citacao', TRUE),
(179, 'Pregue Cristo, Cristo, Cristo — até que as pessoas fiquem cansadas de ouvir… e então pregue Cristo de novo.', 'Charles Spurgeon', 'citacao', TRUE),
(180, 'Sem a cruz, não há evangelho; sem Cristo, não há esperança.', 'Charles Spurgeon', 'citacao', TRUE),
(181, 'A oração move a mão que move o mundo.', 'Charles Spurgeon', 'citacao', TRUE),
(182, 'Cresça em graça: quem não avança em santidade já começou a recuar.', 'Charles Spurgeon', 'citacao', TRUE),
(183, 'O trono da graça nunca está ocupado demais para ouvir o gemido de um pecador.', 'Charles Spurgeon', 'citacao', TRUE),
(184, 'Dai-me cem pregadores que nada temam senão o pecado e desejem apenas a Deus — e abalarei o mundo.', 'John Wesley', 'citacao', TRUE),
(185, 'O mundo é a minha paróquia.', 'John Wesley', 'citacao', TRUE),
(186, 'Faça todo o bem que puder, por todos os meios, a todas as pessoas, enquanto puder.', 'John Wesley', 'citacao', TRUE),
(187, 'Santidade não é luxo; é o caminho do discípulo de Jesus.', 'John Wesley', 'citacao', TRUE),
(188, 'O homem que anda com Deus no secreto raramente tropeça em público.', 'D. L. Moody', 'citacao', TRUE),
(189, 'Deus nunca enviou alguém a uma missão sem primeiro prepará-lo em oração.', 'D. L. Moody', 'citacao', TRUE),
(190, 'O mundo ainda não viu o que Deus pode fazer com um homem totalmente rendido a Cristo.', 'D. L. Moody', 'citacao', TRUE),
(191, 'O que vem à mente quando pensamos em Deus é a coisa mais importante sobre nós.', 'A. W. Tozer', 'citacao', TRUE),
(192, 'A fé verdadeira não nega a realidade; confia em Cristo no meio dela.', 'A. W. Tozer', 'citacao', TRUE),
(193, 'Deus está procurando pessoas através das quais possa fazer o impossível.', 'A. W. Tozer', 'citacao', TRUE),
(194, 'O evangelho é boas-novas porque Cristo fez por nós o que jamais faríamos por nós mesmos.', 'Martyn Lloyd-Jones', 'citacao', TRUE),
(195, 'A pregação verdadeira aponta para fora de nós — para Cristo e sua obra consumada.', 'Martyn Lloyd-Jones', 'citacao', TRUE),
(196, 'Não há cristianismo sem a cruz; e não há cruz sem o Cristo crucificado.', 'John Stott', 'citacao', TRUE),
(197, 'A Bíblia não é o produto da mente humana, mas a revelação do Deus vivo.', 'John Stott', 'citacao', TRUE),
(198, 'O Cristianismo, se for verdadeiro, não é uma religião a mais — é a verdade sobre Cristo.', 'C. S. Lewis', 'citacao', TRUE),
(199, 'Humildade não é pensar menos de si; é pensar menos em si — e mais em Cristo.', 'C. S. Lewis', 'citacao', TRUE),
(200, 'A dor que Deus permite pode ser o cinzel que esculpe Cristo em nós.', 'C. S. Lewis', 'citacao', TRUE),
(201, 'O objetivo da vida cristã não é felicidade imediata, mas semelhança com Jesus.', 'C. S. Lewis', 'citacao', TRUE),
(202, 'Avivamento começa quando o povo de Deus se humilha e busca o rosto de Cristo.', 'Leonard Ravenhill', 'citacao', TRUE),
(203, 'O homem que está em chamas por Cristo é difícil de apagar.', 'Leonard Ravenhill', 'citacao', TRUE),
(204, 'Pregue como se nunca mais fosse pregar; ore como se nunca mais fosse orar.', 'Leonard Ravenhill', 'citacao', TRUE),
(205, 'A grande necessidade da igreja não é de métodos novos, mas de homens cheios do Espírito.', 'E. M. Bounds', 'citacao', TRUE),
(206, 'Homens são o método de Deus; e homens de oração são o poder de Deus.', 'E. M. Bounds', 'citacao', TRUE),
(207, 'Cristo não veio para tornar os maus um pouco melhores, mas para tornar os mortos vivos.', 'Timothy Keller', 'citacao', TRUE),
(208, 'O evangelho diz: você é mais pecador do que imaginava — e mais amado em Cristo do que ousava sonhar.', 'Timothy Keller', 'citacao', TRUE),
(209, 'A graça não é barata; custou o sangue do Filho de Deus.', 'Dietrich Bonhoeffer', 'citacao', TRUE),
(210, 'Quando Cristo chama um homem, Ele o convida a vir e morrer — para viver nele.', 'Dietrich Bonhoeffer', 'citacao', TRUE),
(211, 'A quietude diante de Deus é o solo onde nasce a coragem cristã.', 'Corrie ten Boom', 'citacao', TRUE),
(212, 'Não há poço tão fundo que o amor de Jesus não seja ainda mais profundo.', 'Corrie ten Boom', 'citacao', TRUE),
(213, 'Segure tudo com as mãos abertas; Cristo é o único tesouro que não se perde.', 'Corrie ten Boom', 'citacao', TRUE),
(214, 'O mundo pode tirar tudo, menos a presença de Cristo no coração.', 'Corrie ten Boom', 'citacao', TRUE),
(215, 'Avivamento é a igreja voltando ao primeiro amor: Jesus Cristo.', 'Jonathan Edwards', 'citacao', TRUE),
(216, 'A verdadeira religião consiste numa disposição santa do coração, produzida pelo Espírito.', 'Jonathan Edwards', 'citacao', TRUE),
(217, 'Resolvi não saber coisa alguma entre vós, senão a Jesus Cristo, e este crucificado.', 'George Whitefield', 'citacao', TRUE),
(218, 'Pregue Cristo até que o povo sinta o peso do pecado e a doçura da graça.', 'George Whitefield', 'citacao', TRUE),
(219, 'A cruz não é um enfeite; é o poder de Deus para salvação.', 'R. C. Sproul', 'citacao', TRUE),
(220, 'Deus é santo — e em Cristo o pecador encontra refúgio.', 'R. C. Sproul', 'citacao', TRUE),
(221, 'A soberania de Deus não anula a oração; ela a torna poderosa.', 'R. C. Sproul', 'citacao', TRUE),
(222, 'Viva de modo que, se alguém negar o evangelho, sua vida o contradiga.', 'Francis Schaeffer', 'citacao', TRUE),
(223, 'Cristo é Senhor sobre toda a vida — não apenas sobre o domingo.', 'Abraham Kuyper', 'citacao', TRUE),
(224, 'Não há um centímetro do universo sobre o qual Cristo não diga: É meu.', 'Abraham Kuyper', 'citacao', TRUE),
(225, 'Comece o dia aos pés de Cristo; o resto encontra ordem na presença Dele.', 'Mensagem de ânimo', 'animo', TRUE),
(226, 'Sua identidade não está no que você produz, mas em quem Cristo diz que você é.', 'Mensagem de ânimo', 'animo', TRUE),
(227, 'Quando a ansiedade gritar, responda com a Palavra: o Senhor pelejará por você.', 'Mensagem de ânimo', 'animo', TRUE),
(228, 'Fracasso não é o fim para quem está em Cristo — é escola de dependência.', 'Mensagem de ânimo', 'animo', TRUE),
(229, 'Seja fiel no pouco; o Senhor dos muito está olhando o coração.', 'Mensagem de ânimo', 'animo', TRUE),
(230, 'A cruz prova que você nunca foi esquecido — foi amado até o fim.', 'Mensagem de ânimo', 'animo', TRUE),
(231, 'Ore antes de decidir; Cristo guia os que esperam nele.', 'Mensagem de ânimo', 'animo', TRUE),
(232, 'Santidade não é perfeição humana; é caminhar com Jesus um passo de cada vez.', 'Mensagem de ânimo', 'animo', TRUE),
(233, 'O evangelho não é para pessoas que se acham fortes; é para quem admite precisar de um Salvador.', 'Mensagem de ânimo', 'animo', TRUE),
(234, 'Hoje, escolha servir como Jesus serviu: com humildade e verdade.', 'Mensagem de ânimo', 'animo', TRUE),
(235, 'A esperança cristã não é otimismo barato; é confiança na ressurreição.', 'Mensagem de ânimo', 'animo', TRUE),
(236, 'Perdoe como foste perdoado em Cristo — liberdade começa aí.', 'Mensagem de ânimo', 'animo', TRUE),
(237, 'Sua casa pode ser um altar: ore, leia a Bíblia, honre a Cristo juntos.', 'Mensagem de ânimo', 'animo', TRUE),
(238, 'Não compare sua jornada; corra a carreira que Cristo marcou para você.', 'Mensagem de ânimo', 'animo', TRUE),
(239, 'O silêncio de Deus não é ausência; muitas vezes é formação.', 'Mensagem de ânimo', 'animo', TRUE),
(240, 'Seja luz no trabalho: ética, gentileza e excelência para a glória de Deus.', 'Mensagem de ânimo', 'animo', TRUE),
(241, 'A Bíblia aberta e o joelho dobrado mudam o rumo de um dia.', 'Mensagem de ânimo', 'animo', TRUE),
(242, 'Cristo não prometeu ausência de tempestade; prometeu presença nela.', 'Mensagem de ânimo', 'animo', TRUE),
(243, 'Arrependimento é presente: volta para o Pai pelo Filho.', 'Mensagem de ânimo', 'animo', TRUE),
(244, 'Guarde o coração; dele procedem as fontes da vida — e Cristo o guarda.', 'Mensagem de ânimo', 'animo', TRUE),
(245, 'A oração não informa Deus; alinha você ao Senhorio de Jesus.', 'Mensagem de ânimo', 'animo', TRUE),
(246, 'Seja grato: a gratidão é o idioma dos resgatados pela cruz.', 'Mensagem de ânimo', 'animo', TRUE),
(247, 'Não desista: Aquele que começou a boa obra em você há de completá-la.', 'Mensagem de ânimo', 'animo', TRUE),
(248, 'A verdade em amor edifica; fale como quem pertence a Cristo.', 'Mensagem de ânimo', 'animo', TRUE),
(249, 'O domingo nutre a semana; a semana testemunha do domingo — tudo para Jesus.', 'Mensagem de ânimo', 'animo', TRUE),
(250, 'Quando o medo bater à porta, deixe a fé em Cristo atender.', 'Mensagem de ânimo', 'animo', TRUE),
(251, 'Seja um canal de graça: alguém precisa do evangelho que você vive.', 'Mensagem de ânimo', 'animo', TRUE),
(252, 'A disciplina espiritual não é legalismo; é amor que busca o Senhor.', 'Mensagem de ânimo', 'animo', TRUE),
(253, 'Descanso em Cristo não é preguiça; é confiança que trabalha sem ansiedade.', 'Mensagem de ânimo', 'animo', TRUE),
(254, 'O sangue de Jesus fala melhor coisas: perdão, limpeza e acesso ao Pai.', 'Mensagem de ânimo', 'animo', TRUE),
(255, 'Avance em missão: onde você está, ali há um campo para testemunhar Cristo.', 'Mensagem de ânimo', 'animo', TRUE),
(256, 'A pureza do coração vê a Deus — peça olhos limpos para hoje.', 'Mensagem de ânimo', 'animo', TRUE),
(257, 'Não tenha vergonha do evangelho: nele está o poder de Deus.', 'Mensagem de ânimo', 'animo', TRUE),
(258, 'Cristo é suficiente — ontem, hoje e quando amanhã parecer impossível.', 'Mensagem de ânimo', 'animo', TRUE),
(259, 'Sirva na igreja local com alegria: o corpo de Cristo precisa de cada membro.', 'Mensagem de ânimo', 'animo', TRUE),
(260, 'A Bíblia não é enfeite; é pão diário para a alma.', 'Mensagem de ânimo', 'animo', TRUE),
(261, 'Escolha a estreita: o caminho largo aplaude; o estreito salva.', 'Mensagem de ânimo', 'animo', TRUE),
(262, 'A cruz desarma o orgulho e levanta o quebrantado.', 'Mensagem de ânimo', 'animo', TRUE),
(263, 'Jesus não apenas melhora a vida; Ele é a vida.', 'Mensagem de ânimo', 'animo', TRUE),
(264, 'Hoje é dia de graça: aproveite para amar, perdoar e adorar.', 'Mensagem de ânimo', 'animo', TRUE),
(265, 'O Espírito Santo é Consolador — você não caminha sozinho.', 'Mensagem de ânimo', 'animo', TRUE),
(266, 'Faça da excelência no trabalho um culto a Deus.', 'Mensagem de ânimo', 'animo', TRUE),
(267, 'A fé verdadeira produz obras; as obras nunca substituem a fé em Cristo.', 'Mensagem de ânimo', 'animo', TRUE),
(268, 'Guarde o sábado do coração: reserve tempo real com o Senhor.', 'Mensagem de ânimo', 'animo', TRUE),
(269, 'A esperança que não decepciona foi derramada em nossos corações pelo Espírito.', 'Mensagem de ânimo', 'animo', TRUE),
(270, 'Seja paciente: Deus escreve histórias longas com final em Cristo.', 'Mensagem de ânimo', 'animo', TRUE),
(271, 'A humildade abre portas que o orgulho tranca.', 'Mensagem de ânimo', 'animo', TRUE),
(272, 'O Senhor conhece seu nome — e chama você a segui-lo hoje.', 'Mensagem de ânimo', 'animo', TRUE),
(273, 'Viva preparado: Cristo virá; até lá, seja fiel.', 'Mensagem de ânimo', 'animo', TRUE),
(274, 'A igreja não é um clube; é a noiva de Cristo — ame-a e sirva-a.', 'Mensagem de ânimo', 'animo', TRUE),
(275, 'Quando errar, corra para a cruz — não para as desculpas.', 'Mensagem de ânimo', 'animo', TRUE),
(276, 'A bondade de Deus leva ao arrependimento; receba-a com coração brando.', 'Mensagem de ânimo', 'animo', TRUE),
(277, 'Seja generoso: quem semeia com alegria honra o Doador de tudo.', 'Mensagem de ânimo', 'animo', TRUE),
(278, 'A paz de Cristo governe o seu coração — e a sua agenda.', 'Mensagem de ânimo', 'animo', TRUE),
(279, 'Não negocie a verdade por conforto; Cristo é a verdade.', 'Mensagem de ânimo', 'animo', TRUE),
(280, 'O discípulo carrega a cruz diária — e encontra alegria nela.', 'Mensagem de ânimo', 'animo', TRUE),
(281, 'Ore pelos líderes; ore pelos perdidos; ore com fé.', 'Mensagem de ânimo', 'animo', TRUE),
(282, 'A família precisa de Cristo no centro, não na periferia.', 'Mensagem de ânimo', 'animo', TRUE),
(283, 'Seja íntegro quando ninguém vê: o Senhor vê.', 'Mensagem de ânimo', 'animo', TRUE),
(284, 'A missão não espera perfeição; espera obediência.', 'Mensagem de ânimo', 'animo', TRUE),
(285, 'Cristo venceu a morte — o maior medo humano já caiu.', 'Mensagem de ânimo', 'animo', TRUE),
(286, 'Leia um capítulo; ore uma oração sincera; ame uma pessoa — comece simples.', 'Mensagem de ânimo', 'animo', TRUE),
(287, 'A graça não desculpa o pecado; ela capacita a santidade.', 'Mensagem de ânimo', 'animo', TRUE),
(288, 'O Senhor restaura almas cansadas — traga a sua hoje.', 'Mensagem de ânimo', 'animo', TRUE),
(289, 'Seja sal: preserve o bem e dê sabor ao evangelho onde estiver.', 'Mensagem de ânimo', 'animo', TRUE),
(290, 'A palavra de Cristo habite em você — e saia em palavras de vida.', 'Mensagem de ânimo', 'animo', TRUE),
(291, 'Não tema o amanhã: Ele já está lá.', 'Mensagem de ânimo', 'animo', TRUE),
(292, 'Adore em espírito e em verdade — o Pai busca tais adoradores.', 'Mensagem de ânimo', 'animo', TRUE),
(293, 'A cruz é o centro da história — e pode ser o centro do seu dia.', 'Mensagem de ânimo', 'animo', TRUE),
(294, 'Alegre-se: o túmulo está vazio e o trono está ocupado por Jesus.', 'Mensagem de ânimo', 'animo', TRUE),
(295, 'Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna.', 'João 3:16', 'versiculo', TRUE),
(296, 'Tudo posso naquele que me fortalece.', 'Filipenses 4:13', 'versiculo', TRUE),
(297, 'O Senhor é o meu pastor; nada me faltará.', 'Salmos 23:1', 'versiculo', TRUE),
(298, 'Entrega o teu caminho ao Senhor; confia nele, e ele tudo fará.', 'Salmos 37:5', 'versiculo', TRUE),
(299, 'Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus.', 'Isaías 41:10', 'versiculo', TRUE),
(300, 'Buscai primeiro o Reino de Deus, e a sua justiça, e todas estas coisas vos serão acrescentadas.', 'Mateus 6:33', 'versiculo', TRUE),
(301, 'Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei.', 'Mateus 11:28', 'versiculo', TRUE),
(302, 'Eu sou o caminho, e a verdade, e a vida; ninguém vem ao Pai senão por mim.', 'João 14:6', 'versiculo', TRUE),
(303, 'Se Deus é por nós, quem será contra nós?', 'Romanos 8:31', 'versiculo', TRUE),
(304, 'Todas as coisas cooperam para o bem daqueles que amam a Deus.', 'Romanos 8:28', 'versiculo', TRUE),
(305, 'O amor é paciente, o amor é bondoso. Não inveja, não se vangloria, não se orgulha.', '1 Coríntios 13:4', 'versiculo', TRUE),
(306, 'Sejam fortes e corajosos. Não tenham medo nem fiquem apavorados, pois o Senhor, o seu Deus, vai com vocês.', 'Deuteronômio 31:6', 'versiculo', TRUE),
(307, 'Lança o teu cuidado sobre o Senhor, e ele te susterá.', 'Salmos 55:22', 'versiculo', TRUE),
(308, 'A alegria do Senhor é a nossa força.', 'Neemias 8:10', 'versiculo', TRUE),
(309, 'Confia no Senhor de todo o teu coração e não te estribes no teu próprio entendimento.', 'Provérbios 3:5', 'versiculo', TRUE),
(310, 'Em todas as tuas vias reconhece-o, e ele endireitará as tuas veredas.', 'Provérbios 3:6', 'versiculo', TRUE),
(311, 'Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará.', 'Salmos 91:1', 'versiculo', TRUE),
(312, 'O Senhor é a minha luz e a minha salvação; a quem temerei?', 'Salmos 27:1', 'versiculo', TRUE),
(313, 'Cria em mim, ó Deus, um coração puro e renova em mim um espírito reto.', 'Salmos 51:10', 'versiculo', TRUE),
(314, 'Bem-aventurados os que têm fome e sede de justiça, porque eles serão fartos.', 'Mateus 5:6', 'versiculo', TRUE),
(315, 'Vós sois a luz do mundo; não se pode esconder uma cidade edificada sobre um monte.', 'Mateus 5:14', 'versiculo', TRUE),
(316, 'Assim brilhe a vossa luz diante dos homens, para que vejam as vossas boas obras e glorifiquem a vosso Pai.', 'Mateus 5:16', 'versiculo', TRUE),
(317, 'Não andeis ansiosos de coisa alguma; antes, em tudo, sejam os vossos pedidos conhecidos diante de Deus.', 'Filipenses 4:6', 'versiculo', TRUE),
(318, 'E a paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos sentimentos em Cristo Jesus.', 'Filipenses 4:7', 'versiculo', TRUE),
(319, 'Porque pela graça sois salvos, por meio da fé; e isto não vem de vós; é dom de Deus.', 'Efésios 2:8', 'versiculo', TRUE),
(320, 'Revesti-vos de toda a armadura de Deus, para que possais estar firmes contra as ciladas do diabo.', 'Efésios 6:11', 'versiculo', TRUE),
(321, 'Sede, pois, imitadores de Deus, como filhos amados.', 'Efésios 5:1', 'versiculo', TRUE),
(322, 'Andai em amor, como também Cristo vos amou.', 'Efésios 5:2', 'versiculo', TRUE),
(323, 'O fruto do Espírito é: amor, alegria, paz, longanimidade, benignidade, bondade, fidelidade.', 'Gálatas 5:22', 'versiculo', TRUE),
(324, 'Já não sou eu quem vive, mas Cristo vive em mim.', 'Gálatas 2:20', 'versiculo', TRUE),
(325, 'Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna em Cristo Jesus.', 'Romanos 6:23', 'versiculo', TRUE),
(326, 'Não vos conformeis com este século, mas transformai-vos pela renovação da vossa mente.', 'Romanos 12:2', 'versiculo', TRUE),
(327, 'Amai-vos cordialmente uns aos outros com amor fraternal.', 'Romanos 12:10', 'versiculo', TRUE),
(328, 'Eis que estou à porta e bato; se alguém ouvir a minha voz e abrir a porta, entrarei.', 'Apocalipse 3:20', 'versiculo', TRUE),
(329, 'Eu sou o Alfa e o Ômega, o princípio e o fim, diz o Senhor.', 'Apocalipse 1:8', 'versiculo', TRUE),
(330, 'Sede santos, porque eu sou santo.', '1 Pedro 1:16', 'versiculo', TRUE),
(331, 'Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.', '1 Pedro 5:7', 'versiculo', TRUE),
(332, 'Mas o Deus de toda a graça… vos aperfeiçoará, confirmará, fortificará e estabelecerá.', '1 Pedro 5:10', 'versiculo', TRUE),
(333, 'Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar e nos purificar.', '1 João 1:9', 'versiculo', TRUE),
(334, 'Nós amamos porque ele nos amou primeiro.', '1 João 4:19', 'versiculo', TRUE),
(335, 'Deus é amor; e quem permanece em amor permanece em Deus, e Deus nele.', '1 João 4:16', 'versiculo', TRUE),
(336, 'A fé é o firme fundamento das coisas que se esperam e a prova das coisas que se não veem.', 'Hebreus 11:1', 'versiculo', TRUE),
(337, 'Olhando firmemente para o Autor e Consumador da fé, Jesus.', 'Hebreus 12:2', 'versiculo', TRUE),
(338, 'Acheguemo-nos, pois, com confiança ao trono da graça, para que alcancemos misericórdia.', 'Hebreus 4:16', 'versiculo', TRUE),
(339, 'Jesus Cristo é o mesmo ontem, e hoje, e eternamente.', 'Hebreus 13:8', 'versiculo', TRUE),
(340, 'Sede dores da palavra, e não somente ouvintes.', 'Tiago 1:22', 'versiculo', TRUE),
(341, 'A oração feita por um justo pode muito em seus efeitos.', 'Tiago 5:16', 'versiculo', TRUE),
(342, 'O Senhor é bom, um refúgio em tempos de angústia; conhece os que nele confiam.', 'Naum 1:7', 'versiculo', TRUE),
(343, 'Ainda que a figueira não floresça… eu me alegrarei no Senhor.', 'Habacuque 3:17-18', 'versiculo', TRUE),
(344, 'Porque eu bem sei os planos que tenho a vosso respeito, diz o Senhor; planos de paz e não de mal.', 'Jeremias 29:11', 'versiculo', TRUE),
(345, 'Clama a mim, e responder-te-ei e anunciar-te-ei coisas grandes e firmes.', 'Jeremias 33:3', 'versiculo', TRUE),
(346, 'As misericórdias do Senhor são a causa de não sermos consumidos; renovam-se a cada manhã.', 'Lamentações 3:22-23', 'versiculo', TRUE),
(347, 'Eis que faço uma coisa nova; agora sairá à luz; porventura não a percebeis?', 'Isaías 43:19', 'versiculo', TRUE),
(348, 'Mas os que esperam no Senhor renovarão as suas forças; subirão com asas como águias.', 'Isaías 40:31', 'versiculo', TRUE),
(349, 'O Senhor pelejará por vós, e vós vos calareis.', 'Êxodo 14:14', 'versiculo', TRUE),
(350, 'Sede fortes e corajosos; não temais, porque o Senhor vosso Deus é o que vai convosco.', 'Deuteronômio 31:6', 'versiculo', TRUE),
(351, 'Escolhei hoje a quem sirvais… eu e a minha casa serviremos ao Senhor.', 'Josué 24:15', 'versiculo', TRUE),
(352, 'Não por força nem por poder, mas pelo meu Espírito, diz o Senhor dos Exércitos.', 'Zacarias 4:6', 'versiculo', TRUE),
(353, 'Amarás o Senhor teu Deus de todo o teu coração… e ao teu próximo como a ti mesmo.', 'Mateus 22:37-39', 'versiculo', TRUE),
(354, 'Ide, portanto, fazei discípulos de todas as nações.', 'Mateus 28:19', 'versiculo', TRUE),
(355, 'Eis que eu estou convosco todos os dias, até a consumação dos séculos.', 'Mateus 28:20', 'versiculo', TRUE),
(356, 'O Filho do Homem veio buscar e salvar o que se havia perdido.', 'Lucas 19:10', 'versiculo', TRUE),
(357, 'Porque o Filho do Homem não veio para ser servido, mas para servir e dar a sua vida.', 'Marcos 10:45', 'versiculo', TRUE),
(358, 'Arrependei-vos, porque é chegado o Reino dos céus.', 'Mateus 4:17', 'versiculo', TRUE),
(359, 'Bem-aventurados os pacificadores, porque eles serão chamados filhos de Deus.', 'Mateus 5:9', 'versiculo', TRUE),
(360, 'Não julgueis, para que não sejais julgados.', 'Mateus 7:1', 'versiculo', TRUE),
(361, 'Pedi, e dar-se-vos-á; buscai, e encontrareis; batei, e abrir-se-vos-á.', 'Mateus 7:7', 'versiculo', TRUE),
(362, 'Entrai pela porta estreita… estreito é o caminho que conduz à vida.', 'Mateus 7:13-14', 'versiculo', TRUE),
(363, 'Nem só de pão viverá o homem, mas de toda palavra que sai da boca de Deus.', 'Mateus 4:4', 'versiculo', TRUE),
(364, 'Onde estiver o vosso tesouro, aí estará também o vosso coração.', 'Mateus 6:21', 'versiculo', TRUE),
(365, 'Não podeis servir a Deus e às riquezas.', 'Mateus 6:24', 'versiculo', TRUE),
(366, 'Basta a cada dia o seu mal.', 'Mateus 6:34', 'versiculo', TRUE);
