-- Substitui mensagens genéricas ("ânimo") por versículos e citações bem conhecidos.
-- Dias 225–294 (antes: textos inventados + rótulo "Mensagem de ânimo").

UPDATE mensagem_diaria SET texto = 'Tende bom ânimo; eu venci o mundo.', referencia = 'João 16:33', tipo = 'versiculo' WHERE dia_ano = 225;
UPDATE mensagem_diaria SET texto = 'Este é o dia que fez o Senhor; regozijemo-nos e alegremo-nos nele.', referencia = 'Salmos 118:24', tipo = 'versiculo' WHERE dia_ano = 226;
UPDATE mensagem_diaria SET texto = 'A tua palavra é lâmpada para os meus pés e luz para o meu caminho.', referencia = 'Salmos 119:105', tipo = 'versiculo' WHERE dia_ano = 227;
UPDATE mensagem_diaria SET texto = 'Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia.', referencia = 'Salmos 46:1', tipo = 'versiculo' WHERE dia_ano = 228;
UPDATE mensagem_diaria SET texto = 'Levanto os meus olhos para os montes: de onde me virá o socorro? O meu socorro vem do Senhor.', referencia = 'Salmos 121:1-2', tipo = 'versiculo' WHERE dia_ano = 229;
UPDATE mensagem_diaria SET texto = 'O Senhor te guardará de todo o mal; guardará a tua alma.', referencia = 'Salmos 121:7', tipo = 'versiculo' WHERE dia_ano = 230;
UPDATE mensagem_diaria SET texto = 'Provai e vede que o Senhor é bom; bem-aventurado o homem que nele confia.', referencia = 'Salmos 34:8', tipo = 'versiculo' WHERE dia_ano = 231;
UPDATE mensagem_diaria SET texto = 'Perto está o Senhor dos que têm o coração quebrantado.', referencia = 'Salmos 34:18', tipo = 'versiculo' WHERE dia_ano = 232;
UPDATE mensagem_diaria SET texto = 'Bendize, ó minha alma, ao Senhor, e tudo o que há em mim bendiga o seu santo nome.', referencia = 'Salmos 103:1', tipo = 'versiculo' WHERE dia_ano = 233;
UPDATE mensagem_diaria SET texto = 'O Senhor é misericordioso e compassivo; tardio em irar-se e grande em benignidade.', referencia = 'Salmos 103:8', tipo = 'versiculo' WHERE dia_ano = 234;
UPDATE mensagem_diaria SET texto = 'Quanto está longe o oriente do ocidente, assim afasta de nós as nossas transgressões.', referencia = 'Salmos 103:12', tipo = 'versiculo' WHERE dia_ano = 235;
UPDATE mensagem_diaria SET texto = 'Como um pai se compadece de seus filhos, assim o Senhor se compadece dos que o temem.', referencia = 'Salmos 103:13', tipo = 'versiculo' WHERE dia_ano = 236;
UPDATE mensagem_diaria SET texto = 'Celebrai com júbilo ao Senhor, todos os habitantes da terra.', referencia = 'Salmos 100:1', tipo = 'versiculo' WHERE dia_ano = 237;
UPDATE mensagem_diaria SET texto = 'Sabei que o Senhor é Deus; foi ele quem nos fez, e dele somos.', referencia = 'Salmos 100:3', tipo = 'versiculo' WHERE dia_ano = 238;
UPDATE mensagem_diaria SET texto = 'Entrai pelas portas dele com ação de graças e nos seus átrios com louvor.', referencia = 'Salmos 100:4', tipo = 'versiculo' WHERE dia_ano = 239;
UPDATE mensagem_diaria SET texto = 'Grande é o Senhor e muito digno de ser louvado; e a sua grandeza é inescrutável.', referencia = 'Salmos 145:3', tipo = 'versiculo' WHERE dia_ano = 240;
UPDATE mensagem_diaria SET texto = 'Perto está o Senhor de todos os que o invocam, de todos os que o invocam em verdade.', referencia = 'Salmos 145:18', tipo = 'versiculo' WHERE dia_ano = 241;
UPDATE mensagem_diaria SET texto = 'Ainda que eu andasse pelo vale da sombra da morte, não temeria mal algum, porque tu estás comigo.', referencia = 'Salmos 23:4', tipo = 'versiculo' WHERE dia_ano = 242;
UPDATE mensagem_diaria SET texto = 'Bondade e misericórdia me seguirão todos os dias da minha vida.', referencia = 'Salmos 23:6', tipo = 'versiculo' WHERE dia_ano = 243;
UPDATE mensagem_diaria SET texto = 'Não se turbe o vosso coração; credes em Deus, crede também em mim.', referencia = 'João 14:1', tipo = 'versiculo' WHERE dia_ano = 244;
UPDATE mensagem_diaria SET texto = 'Na casa de meu Pai há muitas moradas; vou preparar-vos lugar.', referencia = 'João 14:2', tipo = 'versiculo' WHERE dia_ano = 245;
UPDATE mensagem_diaria SET texto = 'Eu sou o caminho, e a verdade, e a vida; ninguém vem ao Pai senão por mim.', referencia = 'João 14:6', tipo = 'versiculo' WHERE dia_ano = 246;
UPDATE mensagem_diaria SET texto = 'O Consolador, o Espírito Santo, a quem o Pai enviará em meu nome, esse vos ensinará todas as coisas.', referencia = 'João 14:26', tipo = 'versiculo' WHERE dia_ano = 247;
UPDATE mensagem_diaria SET texto = 'Maior é o que está em vós do que o que está no mundo.', referencia = '1 João 4:4', tipo = 'versiculo' WHERE dia_ano = 248;
UPDATE mensagem_diaria SET texto = 'Porque para Deus nada é impossível.', referencia = 'Lucas 1:37', tipo = 'versiculo' WHERE dia_ano = 249;
UPDATE mensagem_diaria SET texto = 'Não temas; crê somente.', referencia = 'Marcos 5:36', tipo = 'versiculo' WHERE dia_ano = 250;
UPDATE mensagem_diaria SET texto = 'Tende bom ânimo, filha; a tua fé te salvou.', referencia = 'Mateus 9:22', tipo = 'versiculo' WHERE dia_ano = 251;
UPDATE mensagem_diaria SET texto = 'O meu Deus, segundo as suas riquezas, suprirá todas as vossas necessidades em glória, por Cristo Jesus.', referencia = 'Filipenses 4:19', tipo = 'versiculo' WHERE dia_ano = 252;
UPDATE mensagem_diaria SET texto = 'Estou bem certo de que aquele que começou boa obra em vós há de completá-la até ao dia de Cristo Jesus.', referencia = 'Filipenses 1:6', tipo = 'versiculo' WHERE dia_ano = 253;
UPDATE mensagem_diaria SET texto = 'Tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor e não aos homens.', referencia = 'Colossenses 3:23', tipo = 'versiculo' WHERE dia_ano = 254;
UPDATE mensagem_diaria SET texto = 'A palavra de Cristo habite em vós ricamente.', referencia = 'Colossenses 3:16', tipo = 'versiculo' WHERE dia_ano = 255;
UPDATE mensagem_diaria SET texto = 'Antes, sede uns para com os outros benignos, misericordiosos, perdoando-vos uns aos outros.', referencia = 'Efésios 4:32', tipo = 'versiculo' WHERE dia_ano = 256;
UPDATE mensagem_diaria SET texto = 'Porque nós somos feitura sua, criados em Cristo Jesus para boas obras.', referencia = 'Efésios 2:10', tipo = 'versiculo' WHERE dia_ano = 257;
UPDATE mensagem_diaria SET texto = 'Não vos sobreveio tentação que não fosse humana; mas Deus é fiel.', referencia = '1 Coríntios 10:13', tipo = 'versiculo' WHERE dia_ano = 258;
UPDATE mensagem_diaria SET texto = 'Portanto, meus amados irmãos, sede firmes e constantes, sempre abundantes na obra do Senhor.', referencia = '1 Coríntios 15:58', tipo = 'versiculo' WHERE dia_ano = 259;
UPDATE mensagem_diaria SET texto = 'Ora, a fé é o firme fundamento das coisas que se esperam e a prova das coisas que se não veem.', referencia = 'Hebreus 11:1', tipo = 'versiculo' WHERE dia_ano = 260;
UPDATE mensagem_diaria SET texto = 'Jesus Cristo é o mesmo ontem, e hoje, e eternamente.', referencia = 'Hebreus 13:8', tipo = 'versiculo' WHERE dia_ano = 261;
UPDATE mensagem_diaria SET texto = 'Antes que eu te formasse no ventre, eu te conheci.', referencia = 'Jeremias 1:5', tipo = 'versiculo' WHERE dia_ano = 262;
UPDATE mensagem_diaria SET texto = 'Não temas, porque eu te remi; chamei-te pelo teu nome, tu és meu.', referencia = 'Isaías 43:1', tipo = 'versiculo' WHERE dia_ano = 263;
UPDATE mensagem_diaria SET texto = 'Eu, eu sou o Senhor, e fora de mim não há salvador.', referencia = 'Isaías 43:11', tipo = 'versiculo' WHERE dia_ano = 264;
UPDATE mensagem_diaria SET texto = 'Bem sei eu que o meu Redentor vive.', referencia = 'Jó 19:25', tipo = 'versiculo' WHERE dia_ano = 265;
UPDATE mensagem_diaria SET texto = 'O Senhor o deu, e o Senhor o tomou; bendito seja o nome do Senhor.', referencia = 'Jó 1:21', tipo = 'versiculo' WHERE dia_ano = 266;
UPDATE mensagem_diaria SET texto = 'Ensina-nos a contar os nossos dias, de tal maneira que alcancemos corações sábios.', referencia = 'Salmos 90:12', tipo = 'versiculo' WHERE dia_ano = 267;
UPDATE mensagem_diaria SET texto = 'Onde estiverem dois ou três reunidos em meu nome, aí estou eu no meio deles.', referencia = 'Mateus 18:20', tipo = 'versiculo' WHERE dia_ano = 268;
UPDATE mensagem_diaria SET texto = 'Vinde, benditos de meu Pai, possuí por herança o reino que vos está preparado.', referencia = 'Mateus 25:34', tipo = 'versiculo' WHERE dia_ano = 269;
UPDATE mensagem_diaria SET texto = 'Bem-aventurados os mansos, porque eles herdarão a terra.', referencia = 'Mateus 5:5', tipo = 'versiculo' WHERE dia_ano = 270;
UPDATE mensagem_diaria SET texto = 'Bem-aventurados os que choram, porque eles serão consolados.', referencia = 'Mateus 5:4', tipo = 'versiculo' WHERE dia_ano = 271;
UPDATE mensagem_diaria SET texto = 'Vós sois o sal da terra.', referencia = 'Mateus 5:13', tipo = 'versiculo' WHERE dia_ano = 272;
UPDATE mensagem_diaria SET texto = 'Não viverei eu, porém o Cristo vive em mim.', referencia = 'Gálatas 2:20', tipo = 'versiculo' WHERE dia_ano = 273;
UPDATE mensagem_diaria SET texto = 'Mas o fruto do Espírito é: amor, alegria, paz, longanimidade, benignidade, bondade, fidelidade, mansidão, domínio próprio.', referencia = 'Gálatas 5:22-23', tipo = 'versiculo' WHERE dia_ano = 274;
UPDATE mensagem_diaria SET texto = 'Levai as cargas uns dos outros e assim cumprireis a lei de Cristo.', referencia = 'Gálatas 6:2', tipo = 'versiculo' WHERE dia_ano = 275;
UPDATE mensagem_diaria SET texto = 'Não vos enganeis: Deus não se deixa escarnecer.', referencia = 'Gálatas 6:7', tipo = 'versiculo' WHERE dia_ano = 276;
UPDATE mensagem_diaria SET texto = 'Porque o reino de Deus não é comida nem bebida, mas justiça, e paz, e alegria no Espírito Santo.', referencia = 'Romanos 14:17', tipo = 'versiculo' WHERE dia_ano = 277;
UPDATE mensagem_diaria SET texto = 'Porque nele vivemos, e nos movemos, e existimos.', referencia = 'Atos 17:28', tipo = 'versiculo' WHERE dia_ano = 278;
UPDATE mensagem_diaria SET texto = 'Crê no Senhor Jesus e serás salvo, tu e a tua casa.', referencia = 'Atos 16:31', tipo = 'versiculo' WHERE dia_ano = 279;
UPDATE mensagem_diaria SET texto = 'Não há salvação em nenhum outro; porque debaixo do céu nenhum outro nome há… pelo qual importa que sejamos salvos.', referencia = 'Atos 4:12', tipo = 'versiculo' WHERE dia_ano = 280;
UPDATE mensagem_diaria SET texto = 'Santificai a Cristo, como Senhor, em vossos corações.', referencia = '1 Pedro 3:15', tipo = 'versiculo' WHERE dia_ano = 281;
UPDATE mensagem_diaria SET texto = 'Antes de tudo, tende ardente amor uns para com os outros.', referencia = '1 Pedro 4:8', tipo = 'versiculo' WHERE dia_ano = 282;
UPDATE mensagem_diaria SET texto = 'Humilhai-vos, pois, debaixo da potente mão de Deus, para que ele, a seu tempo, vos exalte.', referencia = '1 Pedro 5:6', tipo = 'versiculo' WHERE dia_ano = 283;
UPDATE mensagem_diaria SET texto = 'Se Deus é por nós, quem será contra nós?', referencia = 'Romanos 8:31', tipo = 'versiculo' WHERE dia_ano = 284;
UPDATE mensagem_diaria SET texto = 'Quem nos separará do amor de Cristo?', referencia = 'Romanos 8:35', tipo = 'versiculo' WHERE dia_ano = 285;
UPDATE mensagem_diaria SET texto = 'Em todas estas coisas, porém, somos mais do que vencedores, por aquele que nos amou.', referencia = 'Romanos 8:37', tipo = 'versiculo' WHERE dia_ano = 286;
UPDATE mensagem_diaria SET texto = 'Nem a morte, nem a vida… poderá separar-nos do amor de Deus, que está em Cristo Jesus.', referencia = 'Romanos 8:38-39', tipo = 'versiculo' WHERE dia_ano = 287;
UPDATE mensagem_diaria SET texto = 'Porque Deus não nos deu espírito de covardia, mas de poder, de amor e de moderação.', referencia = '2 Timóteo 1:7', tipo = 'versiculo' WHERE dia_ano = 288;
UPDATE mensagem_diaria SET texto = 'Combati o bom combate, completei a carreira, guardei a fé.', referencia = '2 Timóteo 4:7', tipo = 'versiculo' WHERE dia_ano = 289;
UPDATE mensagem_diaria SET texto = 'Toda a Escritura é inspirada por Deus e útil para o ensino.', referencia = '2 Timóteo 3:16', tipo = 'versiculo' WHERE dia_ano = 290;
UPDATE mensagem_diaria SET texto = 'A oração move a mão que move o mundo.', referencia = 'Charles Spurgeon', tipo = 'citacao' WHERE dia_ano = 291;
UPDATE mensagem_diaria SET texto = 'Ore como se tudo dependesse de Deus; trabalhe como se tudo dependesse de você.', referencia = 'Martinho Lutero', tipo = 'citacao' WHERE dia_ano = 292;
UPDATE mensagem_diaria SET texto = 'Deus nunca enviou alguém a uma missão sem primeiro prepará-lo em oração.', referencia = 'D. L. Moody', tipo = 'citacao' WHERE dia_ano = 293;
UPDATE mensagem_diaria SET texto = 'Não há poço tão fundo que o amor de Jesus não seja ainda mais profundo.', referencia = 'Corrie ten Boom', tipo = 'citacao' WHERE dia_ano = 294;
