spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/someliContab
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG
